#!/bin/bash
#SBATCH --job-name=liggghts_s_fib100_2025-03-29_1


#SBATCH --partition=med
#SBATCH --ntasks-per-node=32
#SBATCH --mem=16gb
#SBATCH --time=7-00:00:00
#SBATCH --output=output_%j.log
#SBATCH --error=error_%j.log
pwd; hostname; date
module use /home/suehr/module_files/
module load openmpi/4.1.5
module load vtk
ln -s ~/Projects/LIGGGHTS_CFDRC/src/lmp_auto
mpiexec -np 32 ./lmp_auto < in.s_fib100_1 
date
